### ISSUE TITLE
Disabling messages.

### ISSUE THREAD

**Issue by 0xC1A551C** [MLG-Fortress/ExtraHardMode#122]
Hey, will this plugin still be updated?

Having some issues with the messages still being sent even though I gave the silence perm, set the broadcast/notification/board to false & set the ticks to 0. Thanks

**Comment by RoboMWM** [comment]
Nothing much to say without any details :s

**Comment by RoboMWM** [comment]
Hmm, could be the displaytime in ticks being some sort of overriding factor (since 0 is a special value for most config nodes it seems). Unsure as of right now.

**Comment by 0xC1A551C** [comment]
Seems like it is still happening when I enter the nether with ticks at 1 this time it shows [EHM] in red before the message. Nothing has changed since I posted. No erros or anything. I changed it from notification to tutorial mode. Maybe I'll try broadcast.

**Comment by 0xC1A551C** [comment]
Now it is in white text again, I can't seem to find any errors in the config. Ill post both just in case.
```
####################################################################################################%n#                                  Messages sent by ExtraHardMode                                  #
#                       Messages are only sent for modules that are activated                      #
#                            Modes (has to match exactly, ignores case)                            #
#       Disabled: Message won't be sent even if feature that would sent the message is active      #
#                         One_Time: Will be sent to every player only once                         #
#            Notification: Gets sent every time with a timeout to prevent spamming chat            #
#             Tutorial: Sent a limited number of times and not displayed after 3 times             #
#         Broadcast: Shown to whole server. Only few messages make sense to be broadcasted         #
#                                            Variables:                                            #
#                  $ALLCAPS is a variable and will be filled in for some messages                  #
#                                     $PLAYER: Affected player                                     #
#                            $PLAYERS: If multiple players are affected                            #
#                             $DEATH_MSG: Death message if someone dies                            #
#                                       $ITEMS: a player lost                                      #
####################################################################################################
Messages:
  Display Messages In Scoreboard:
    Enable: false
    Scoreboard Title: '&cExtraHardMode'
    Remove All Color Codes: true
    Notification:
      Enable: false
      Displaytime In Ticks: 600
      Textcolor: YELLOW
    Tutorial:
      Enable: false
      Displaytime In Ticks: 100
      Textcolor: RED
    Broadcast:
      Enable: false
      Displaytime In Ticks: 1200
      Textcolor: GREEN
  NoTorchesHere:
    Mode: notification
    Msg: There's not enough air flow down here for permanent flames. Use another method
      to light your way.
  StoneMiningHelp:
    Mode: notification
    Msg: You'll need an iron or diamond pickaxe to break stone.  Try exploring natural
      formations for exposed ore like coal, which softens stone around it when broken.
  NoPlacingOreAgainstStone:
    Mode: notification
    Msg: Sorry, you can't place ore next to stone.
  RealisticBuilding:
    Mode: notification
    Msg: You can't build while in the air.
  RealisticBuildingBeneath:
    Mode: notification
    Msg: You can't place a block directly beneath you.
  LimitedTorchPlacements:
    Mode: notification
    Msg: It's too soft there to fasten a torch.
  NoCraftingMelonSeeds:
    Mode: notification
    Msg: That appears to be seedless!
  LimitedEndBuilding:
    Mode: notification
    Msg: Sorry, building here is very limited.  You may only break blocks to reach
      ground level.
  DragonFountainTip:
    Mode: notification
    Msg: Congratulations on defeating the dragon!  If you can't reach the fountain
      to jump into the portal, throw an ender pearl at it.
  NoSwimmingInArmor:
    Mode: notification
    Msg: You're carrying too much weight to swim!
  DragonDefeated:
    Mode: notification
    Msg: 'The dragon has been defeated!  ( By: $PLAYERS )'
  PlayerKilledByDragon:
    Mode: notification
    Msg: $PLAYER was killed while fighting the dragon!
  PlayerChallengingDragon:
    Mode: notification
    Msg: $PLAYER is challenging the dragon!
  HorseFeedLow:
    Mode: notification
    Msg: You have saved your horse from starving, but it's still very hungry.
  HorseFeedMiddle:
    Mode: notification
    Msg: Your horse has ate well.
  HorseFeedHigh:
    Mode: notification
    Msg: Your horse is satiated.
  HorseStarveLow:
    Mode: notification
    Msg: Your horse is very tired and needs some food.
  HorseStarveMiddle:
    Mode: notification
    Msg: Your horse is about to starve.
  HorseStarveHigh:
    Mode: notification
    Msg: Your horse is starving, feed it or it will die.
  ChargedCreeper:
    Mode: tutorial
    Msg: Charged Creepers explode instantly when hit. Run!
  BlazeOverworld:
    Mode: tutorial
    Msg: Blazes spawn near lava and their fiery breath causes a big explosion on death!
  BlazeNether:
    Mode: tutorial
    Msg: Blazes spawn everywhere in the Nether and may split on death!
  Magmacube:
    Mode: tutorial
    Msg: These small buggers actually are just disguised blazes!
  Ghast:
    Mode: tutorial
    Msg: These fearsome Ghasts wear invisible arrow deflective armor! Ghasts drop
      a lot more loot as well.
  PigZombieAlwaysAngry:
    Mode: tutorial
    Msg: RUN! Pig Zombies are always angry and hungry!
  PigZombieDropNetherwart:
    Mode: tutorial
    Msg: You can get netherwart from slaying Pig Zombies
  ZombieRespawn:
    Mode: tutorial
    Msg: Zombies might resurrect if not on fire!
  ZombieSlowPlayer:
    Mode: tutorial
    Msg: Zombies slow you down when hit!
  SkeletonDeflectArrows:
    Mode: tutorial
    Msg: Arrows just pass through Skeletons, you gotta go close combat!
  EndermanGeneral:
    Mode: tutorial
    Msg: Enderman can teleport you too!
  CreeperDropTnt:
    Mode: tutorial
    Msg: Creepers may drop activated tnt on death!
  ExtinguishFire:
    Mode: tutorial
    Msg: Putting out fire with your hand will catch you on fire.
  ListLostItemsOnDeath:
    Mode: notification
    Msg: You managed to lose $ITEMS
  InformPlayerOnLostItems:
    Mode: tutorial
    Msg: On death there is a a chance you might lose some of your items!
  BucketFill:
    Mode: tutorial
    Msg: You can pick up water, but once you place it, it evaporates. Get some ice
      if you want to farm!
  AntifarmingUnwatered:
    Mode: tutorial
    Msg: Your crops need sufficient water, otherwise they'll dry out!
  AntifarmingNotEnoughLight:
    Mode: tutorial
    Msg: Your crops require natural light to grow!
  AntifarmingDesert:
    Mode: tutorial
    Msg: Deserts are really dry and nothing grows here!
  AnimalOverCrowd:
    Mode: notification
    Msg: Animals need space! Consider putting them in a bigger area
  NetherWarning:
    Mode: tutorial
    Msg: This is a dangerous place. Make sure you come prepared with arrows and good
      gear.
```

```
ExtraHardMode:
  Config Type: MAIN
  Print Config Header: false
  Print Comments: false
  Enabled Worlds:
  - '@all'
  Bypassing:
    Check For Permission: true
    Creative Mode Bypasses: false
    Operators Bypass: false
  World Rules:
    Mining:
      Inhibit Tunneling:
        Enable: false
        Hardened Blocks:
        - STONE
        Block Placing Ore Next To Stone Exploit: true
        Block Moving Of Stone Blocks With Piston Exploit: true
        Amount of Stone Tool Can Mine (Tool@Blocks):
        - IRON_PICKAXE@32
        - DIAMOND_PICKAXE@64
      Breaking Blocks Softens Surrounding Stone:
        Enable: true
        Apply Physics To Weakened Stone: true
        Blocks (Block@id,id2):
        - COAL_ORE
        - EMERALD_ORE
        - LAPIS_ORE
        - DIAMOND_ORE
        - REDSTONE_ORE
        - GLOWING_REDSTONE_ORE
        - GOLD_ORE
        - IRON_ORE
        Stone Blocks (Stone@data-Cobble@data):
        - STONE-COBBLESTONE
    Torches:
      No Placement Under Y: 5
      No Placement On Soft Materials: false
      Rain Breaks Torches: true
    Play Sounds:
      Torch Fizzing: true
      Creeper Tnt Warning: true
    Breaking Netherrack Starts Fire Percent: 1
    Limited Block Placement: false
    Better Tree Felling: true
  Player:
    Enhanced Environmental Injuries:
      Enable: true
      Fall:
        Dmg Multiplier: 2.0
        Potion Type: SLOW
        Duration (ticks): 80
        Amplifier: 2
      Explosion:
        Dmg Multiplier: 1.0
        Potion Type: CONFUSION
        Duration (ticks): 100
        Amplifier: 3
      Suffocation:
        Dmg Multiplier: 5.0
        Potion Type: NONE
        Duration (ticks): 0
        Amplifier: 0
      Lava:
        Dmg Multiplier: 2.0
        Potion Type: NONE
        Duration (ticks): 0
        Amplifier: 0
      Burning:
        Dmg Multiplier: 1.0
        Potion Type: BLINDNESS
        Duration (ticks): 20
        Amplifier: 1
      Starvation:
        Dmg Multiplier: 2.0
        Potion Type: NONE
        Duration (ticks): 0
        Amplifier: 0
      Drowning:
        Dmg Multiplier: 1.0
        Potion Type: NONE
        Duration (ticks): 0
        Amplifier: 0
    Extinguishing Fires Ignites Player: false
    Death:
      Loose Items On Death:
        Enable: false
        Percentage: 10
        Damage Tools By Percentage: 30
        Keep Heavily Damaged Tools: true
        Tools:
        - DIAMOND_SWORD
        - DIAMOND_SPADE
        - DIAMOND_PICKAXE
        - DIAMOND_AXE
        Blacklisted Items: []
      Override Respawn Health:
        Enable: false
        Percentage: 75
      Respawn Foodlevel: 15
    No Swimming When Too Heavy:
      Enable: false
      Block Elevators/Waterfalls: false
      Max Points: 18.0
      One Piece Of Worn Armor Adds: 2.0
      One Stack Adds: 1.0
      One Tool Adds: 0.5
      Drown Rate: 15
      Overencumbrance Adds To Drown Rate: 2
    Armor Changes:
      Enable: false
      Basespeed: 0.22
      Slowdown Percentage: 40
  General Monster Rules:
    Inhibit Monster Grinders: false
    More Monsters:
      Max Y: 55
      Multiplier: 2
    Monsters Spawn In Light:
      Max Y: 50
      Max Light: 10
      Percentage: 100
  Horses:
    Block Usage Of Chest Below: 55
  Zombies:
    Slow Players:
      Enable: true
      Effect:
        Potion Type: SLOW
        Duration (ticks): 100
        Amplifier: 1
      Stack Effect:
        Enable: false
        Max Strength: 3
    Reanimate:
      Place Skulls: true
      Placed Skulls Drop Percentage: 5
      Percent: 50
  Skeletons:
    Shoot Snowballs:
      Enable: false
      Percent: 20
      Blind Player (ticks): 10
    Shoot Fireworks:
      Enable: true
      Percent: 30
      Knockback Player Velocity: 1.0
    Shoot Fireballs:
      Enable: true
      Percentage: 10
      Player Fireticks: 40
    Shoot Silverfish:
      Enable: true
      Percent: 20
      Kill Silverfish After Skeleton Died: true
      Limit To X Spawned At A Time: 5
      Limit To X Spawned In Total: 15
    Deflect Arrows Percent: 100
    Spawn in End Percent: 10
  Silverfish:
    Cant enter blocks: true
    Drop Cobble: true
    Show Particles To Make Better Visible: true
  Spiders:
    Bonus Underground Spawn Percent: 20
    Drop Web On Death: true
  Creepers:
    Charged Creeper Spawn Percent: 10
    Drop Tnt On Death:
      Percent: 20
      Max Y: 50
    Charged Creepers Explode On Damage: true
    Fire Triggers Explosion:
      Enable: true
      Firework Count: 3
      Launch In Air Speed: 0.5
  Blazes:
    Near Bedrock Spawn Percent: 20
    Block Drops In Overworld: false
    Bonus Nether Spawn Percent: 20
    Drop Fire On Damage: false
    Bonus Loot: false
    Nether Split On Death Percent: 15
  MagmaCubes:
    Spawn With Nether Blaze Percent: 50
    Grow Into Blazes On Damage: true
  PigZombies:
    Always Angry: false
    Dmg to players percent: 70
    Always Drop Netherwart In Fortresses: true
    Percent Chance to Drop Netherwart Elsewhere In Nether: 25
    Spawn on Lighting Strikes:
      Enable: true
  Ghasts:
    Arrows Do % Damage: 20
    Exp Multiplier: 10
    Drops Multiplier: 5
  Endermen:
    May Teleport Players: true
  Witches:
    Additional Attacks: true
    Bonus Spawn Percent: 5
  KillerBunny:
    Bonus Spawn Percent: 1
  Vindicator:
    Bonus Spawn Percent: 20
  CaveSpider:
    Bonus Spawn Percent: 5
  Guardians:
    Bonus Spawn Percent: 20
  Vex:
    Bonus Spawn Percent: 5
  EnderDragon:
    Respawns: true
    Drops Dragonegg: true
    Drops 2 Villager Eggs: true
    Harder Battle: false
    Alternative Minions: false
    Battle Announcements: false
    No Building Allowed: false
    Health: 500
  Farming:
    Weak Crops:
      Enable: false
      Loss Rate: 25
      Infertile Deserts: false
      Snow Breaks Crops: true
    Cant Craft Melonseeds: true
    No Bonemeal On Mushrooms: true
    No Farming Nether Wart: false
    Sheep Grow Only White Wool: false
    Squid Only Spawn In Ocean: true
    Buckets Dont Move Water Sources: false
    Animal Experience Nerf: true
    Iron Golem Nerf: true
    Animal Overcrowding Control:
      Enable: false
      Threshold: 10
  Additional Falling Blocks:
    Enable: false
    Break Torches: true
    Drop As Items: false
    Landed Blocks Can Cause Blocks To Fall: true
    Dmg Amount When Hitting Players: 2
    Turn Mycel/Grass To Dirt: true
    Enabled Blocks:
    - MOSSY_COBBLESTONE
    - GRASS
    - DIRT
    - COBBLESTONE
    - DOUBLE_STEP@3
    - STEP@3,11
    - MYCEL
  Explosions:
    Turn Stone To Cobble: false
    Physics:
      Enable: false
      Enable For Plugin Created Explosions: false
      Blocks Affected Percentage: 20
      Up Velocity: 2.0
      Spread Velocity: 3.0
      Exceed Radius Autoremove: 10
    Border Y: 55
    Creeper:
      Enable Custom Explosion: false
      Below Border:
        Explosion Power: 3
        Set Fire: false
        World Damage: false
      Above Border:
        Explosion Power: 3
        Set Fire: false
        World Damage: false
    Charged Creeper:
      Enable Custom Explosion: true
      Below Border:
        Explosion Power: 4
        Set Fire: false
        World Damage: false
      Above Border:
        Explosion Power: 4
        Set Fire: false
        World Damage: false
    Tnt:
      Enable Custom Explosion: true
      Enable Multiple Explosions: true
      Tnt Per Recipe: 3
      Below Border:
        Explosion Power: 5
        Set Fire: false
        World Damage: false
      Above Border:
        Explosion Power: 3
        Set Fire: false
        World Damage: false
    Blazes Explode On Death:
      Enable: false
      Below Border:
        Explosion Power: 4
        Set Fire: false
        World Damage: false
      Above Border:
        Explosion Power: 4
        Set Fire: false
        World Damage: false
    Ghasts:
      Enable Custom Explosion: true
      Below Border:
        Explosion Power: 2
        Set Fire: true
        World Damage: false
      Above Border:
        Explosion Power: 2
        Set Fire: true
        World Damage: false
```

**Comment by mirolm** [comment]
I have managed to disable all messages. You can check my config files:

[config.yml](https://hastebin.com/wahakofifi.coffeescript)
[messages.yml](https://hastebin.com/epihahojoq.coffeescript)

Hope it helps.

**Comment by RoboMWM** [comment]
Hastebin's expire @mirolm 

Feel free to paste directly in a comment (within a markdown codeblock).

    ```yaml
    Like so
    ```

**Comment by mirolm** [comment]
Sorry about the delay. :) To make the plugin completely silent i do like below:

```yaml
####################################################################################################%n#                                  Messages sent by ExtraHardMode                                  #
#                       Messages are only sent for modules that are activated                      #
#                            Modes (has to match exactly, ignores case)                            #
#       Disabled: Message won't be sent even if feature that would sent the message is active      #
#                         One_Time: Will be sent to every player only once                         #
#            Notification: Gets sent every time with a timeout to prevent spamming chat            #
#             Tutorial: Sent a limited number of times and not displayed after 3 times             #
#         Broadcast: Shown to whole server. Only few messages make sense to be broadcasted         #
#                                            Variables:                                            #
#                  $ALLCAPS is a variable and will be filled in for some messages                  #
#                                     $PLAYER: Affected player                                     #
#                            $PLAYERS: If multiple players are affected                            #
#                             $DEATH_MSG: Death message if someone dies                            #
#                                       $ITEMS: a player lost                                      #
####################################################################################################
Messages:
  Display Messages In Scoreboard:
    Enable: false
    Scoreboard Title: '&cExtraHardMode'
    Remove All Color Codes: true
    Notification:
      Enable: false
      Displaytime In Ticks: 600
      Textcolor: YELLOW
    Tutorial:
      Enable: false
      Displaytime In Ticks: 1800
      Textcolor: RED
    Broadcast:
      Enable: false
      Displaytime In Ticks: 1200
      Textcolor: GREEN
  NoTorchesHere:
    Mode: disabled
    Msg: There's not enough air flow down here for permanent flames. Use another method
      to light your way.
  StoneMiningHelp:
    Mode: disabled
    Msg: You'll need an iron or diamond pickaxe to break stone.  Try exploring natural
      formations for exposed ore like coal, which softens stone around it when broken.
  NoPlacingOreAgainstStone:
    Mode: disabled
    Msg: Sorry, you can't place ore next to stone.
  RealisticBuilding:
    Mode: disabled
    Msg: You can't build while in the air.
  RealisticBuildingBeneath:
    Mode: disabled
    Msg: You can't place a block directly beneath you.
  LimitedTorchPlacements:
    Mode: disabled
    Msg: It's too soft there to fasten a torch.
  NoCraftingMelonSeeds:
    Mode: disabled
    Msg: That appears to be seedless!
  LimitedEndBuilding:
    Mode: disabled
    Msg: Sorry, building here is very limited.  You may only break blocks to reach
      ground level.
  DragonFountainTip:
    Mode: disabled
    Msg: Congratulations on defeating the dragon!  If you can't reach the fountain
      to jump into the portal, throw an ender pearl at it.
  NoSwimmingInArmor:
    Mode: disabled
    Msg: You're carrying too much weight to swim!
  DragonDefeated:
    Mode: disabled
    Msg: 'The dragon has been defeated!  ( By: $PLAYERS )'
  PlayerKilledByDragon:
    Mode: disabled
    Msg: $PLAYER was killed while fighting the dragon!
  PlayerChallengingDragon:
    Mode: disabled
    Msg: $PLAYER is challenging the dragon!
  HorseFeedLow:
    Mode: disabled
    Msg: You have saved your horse from starving, but it's still very hungry.
  HorseFeedMiddle:
    Mode: disabled
    Msg: Your horse has ate well.
  HorseFeedHigh:
    Mode: disabled
    Msg: Your horse is satiated.
  HorseStarveLow:
    Mode: disabled
    Msg: Your horse is very tired and needs some food.
  HorseStarveMiddle:
    Mode: disabled
    Msg: Your horse is about to starve.
  HorseStarveHigh:
    Mode: disabled
    Msg: Your horse is starving, feed it or it will die.
  ChargedCreeper:
    Mode: disabled
    Msg: Charged Creepers explode instantly when hit. Run!
  BlazeOverworld:
    Mode: disabled
    Msg: Blazes spawn near lava and their fiery breath causes a big explosion on death!
  BlazeNether:
    Mode: disabled
    Msg: Blazes spawn everywhere in the Nether and may split on death!
  Magmacube:
    Mode: disabled
    Msg: These small buggers actually are just disguised blazes!
  Ghast:
    Mode: disabled
    Msg: These fearsome Ghasts wear invisible arrow deflective armor! Ghasts drop
      a lot more loot as well.
  PigZombieAlwaysAngry:
    Mode: disabled
    Msg: RUN! Pig Zombies are always angry and hungry!
  PigZombieDropNetherwart:
    Mode: disabled
    Msg: You can get netherwart from slaying Pig Zombies
  ZombieRespawn:
    Mode: disabled
    Msg: Zombies might resurrect if not on fire!
  ZombieSlowPlayer:
    Mode: disabled
    Msg: Zombies slow you down when hit!
  SkeletonDeflectArrows:
    Mode: disabled
    Msg: Arrows just pass through Skeletons, you gotta go close combat!
  EndermanGeneral:
    Mode: disabled
    Msg: Enderman can teleport you too!
  CreeperDropTnt:
    Mode: disabled
    Msg: Creepers may drop activated tnt on death!
  ExtinguishFire:
    Mode: disabled
    Msg: Putting out fire with your hand will catch you on fire.
  ListLostItemsOnDeath:
    Mode: disabled
    Msg: You managed to lose $ITEMS
  InformPlayerOnLostItems:
    Mode: disabled
    Msg: On death there is a a chance you might lose some of your items!
  BucketFill:
    Mode: disabled
    Msg: You can pick up water, but once you place it, it evaporates. Get some ice
      if you want to farm!
  AntifarmingUnwatered:
    Mode: disabled
    Msg: Your crops need sufficient water, otherwise they'll dry out!
  AntifarmingNotEnoughLight:
    Mode: disabled
    Msg: Your crops require natural light to grow!
  AntifarmingDesert:
    Mode: disabled
    Msg: Deserts are really dry and nothing grows here!
  AnimalOverCrowd:
    Mode: disabled
    Msg: Animals need space! Consider putting them in a bigger area
  NetherWarning:
    Mode: disabled
    Msg: This is a dangerous place. Make sure you come prepared with arrows and good
      gear.
  ChatPrefix: '[EHM]'
```
